### PR TITLE
Wilder wildcards + testing

### PR DESCRIPTION
**Pull request by JasonMillward**
Takes care of #17 while keeping existing functionality.

### CODE REVIEW

**Comment by romainrhd** [comment]
Can you accept the pull request please ? I need this problem is solved

**Comment by mabasic** [comment]
Sure thing, looks good to me. Let me just get back home.

**Comment by mabasic** [comment]
Can you change the test for this so that it checks with `frontend.users.show.stats` and `isActiveRoute('frontend.users.*)`. It should return `active` (true).

**Comment by JasonMillward** [comment]
Test route has been changed

**Pull request merged**
